# 默认配置
server:
  port: 9380
spring:
  application:
    name: shardingsphere-encrypt-jdbc-demo
  profiles:
    active: dev

# mybatis-plus
mybatis-plus:
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
      table-underline: true
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: com.leeyom.shardingsphere.domain.entity

# 监控
javamelody:
  enabled: true
  init-parameters:
    log: true